### ISSUE TITLE
TASK: Add delete hypercert-blueprint functionality

### ISSUE THREAD

**Issue by benedictvscriticus** [hypercerts-org/hypercerts#1101] opened 2023-09-22 19:08 UTC

**Comment by benedictvscriticus** [comment] 2023-09-22 19:18
Is this a duplicate of #1091?

**Comment by Jipperism** [comment] 2023-10-23 08:46
Closing as duplicate of https://github.com/hypercerts-org/hypercerts/issues/1091

**Closed by Jipperism** 2023-10-23 08:46 UTC
Labels: category:frontend
