### ISSUE TITLE
TASK: Add detail view for hypercert-blueprints for hyperboard owners

### ISSUE THREAD

**Issue by benedictvscriticus** [hypercerts-org/hypercerts#1102] opened 2023-09-22 19:08 UTC

**Comment by benedictvscriticus** [comment] 2023-09-22 19:15
@Jipperism this sounds very similar to #1092

**Comment by Jipperism** [comment] 2023-10-23 08:46
Closing as duplicate of https://github.com/hypercerts-org/hypercerts/issues/1092

**Closed by Jipperism** 2023-10-23 08:46 UTC
Labels: category:frontend
