### ISSUE TITLE
bug: check for acceptance of terms doesn't work after connecting wallet

### ISSUE THREAD

**Issue by holkeb** [hypercerts-org/hypercerts#263] opened 2023-02-13 17:27 UTC
Steps to produce error to stops me from minting:
1) wallet not connected + terms not accepted: click "create hypercert" --> correct error message (terms not accepted)
2) accept term + click "create hypercert" --> correct error message (wallet not connected)
2) connect wallet + click "create hypercert" --> wrong error message (terms not accepted)

**Comment by ryscheng** [comment] 2023-02-15 20:18
![Screenshot from 2023-02-15 12-17-05](https://user-images.githubusercontent.com/566890/219143386-36d83516-dbc6-47c8-afe3-13cd0208ef80.png)

Spent a little time on this, we're passing in the correct props into the checkbox (false), but it still shows that it's checked. So that's telling me the visual box doesn't reflect the actual state underneath.
I can't tell if this is a MUI bug or if we need to do something else. Going to P2 this for now

**Comment by ccerv1** [comment] 2023-02-27 11:00
I also see this state every time I try to mint a hypercert and there's an error in the form. To reproduce:

- Create a new hypercert
- Leave a field blank (eg, description)
- Check the two boxes and click "create"
- It will fail to mint
- Review the form for errors
- Fix the error (eg, description)
- The two boxes are still checked so it will appear that you're ready to mint
- Click "create"
- It fails to mint with the above error

Anyway, marking as a P1 "should have" fix for this week, since it's likely that >20% of users will have some error in their form and probably encounter this error.

**Comment by ryscheng** [comment] 2023-03-01 03:18
After some digging, I think I fixed it here
https://github.com/hypercerts-org/hypercerts/pull/418

Went thru both Carl and Holke's steps to reproduce and seems to work okay!

**Closed by ryscheng** 2023-03-01 03:18 UTC
Labels: p1:ready, category:frontend
