### ISSUE TITLE
[Bug] Can't claim lots of fractions (e.g. 950)

### ISSUE THREAD

**Issue by holkexyz** [hypercerts-org/hypercerts#935] opened 2023-07-06 22:19 UTC
I tried to claim 950 fractions 😅  and it was for quite some time in the "Getting and verifying proofs" and then the following error came up. My guess is that having that many fractions might be difficult, is that right?

![Image](https://github.com/hypercerts-org/hypercerts/assets/103380539/ed8a0be6-1bcd-4282-bc8e-c4a543d9790a)

![Image](https://github.com/hypercerts-org/hypercerts/assets/103380539/a057e5c0-b89f-4802-b741-91a9d6601d65)

**Comment by bitbeckers** [comment] 2023-07-07 15:55
On AlreadyClaimed:

The issue is in this piece of code in the allowlistminter:
```js
   function _processClaim(bytes32[] calldata proof, uint256 claimID, uint256 amount) internal {
        if (merkleRoots[claimID].length == 0) revert Errors.DoesNotExist();

        bytes32 leaf = _calculateLeaf(msg.sender, amount);

        if (hasBeenClaimed[claimID][leaf]) revert Errors.AlreadyClaimed();
        if (
            !MerkleProofUpgradeable.verifyCalldata(proof, merkleRoots[claimID], leaf) ||
            (minted[claimID] + amount) > maxUnits[claimID]
        ) revert Errors.Invalid();
        hasBeenClaimed[claimID][leaf] = true;

        emit LeafClaimed(claimID, leaf);
    }

    function _calculateLeaf(address account, uint256 amount) internal pure returns (bytes32 leaf) {
        leaf = keccak256(bytes.concat(keccak256(abi.encode(account, amount))));
    }
```

Leafs are calculated based on addres and units. Holke made an allowlist that basically breaks this flow since there are multiple duplicate address + unit combinations:

```
index    address    fractions
0    0xAB06ca02096257Fe2422F492880D198D685975AD    200
1    0xAB06ca02096257Fe2422F492880D198D685975AD    200
```

We can update with something similar as in supabase: address + amount + index and that should circumvent this.

**Comment by bitbeckers** [comment] 2023-07-07 16:04
Multiproofs as part of the flow? https://github.com/OpenZeppelin/merkle-tree

**Comment by bitbeckers** [comment] 2023-10-06 14:05
@holkeb could you try this again? Or do you have an allowlist available so I can reproduce it? The solutions discussed above have been impleted a while so maybe we forgot to double check..

**Comment by holkeb** [comment] 2023-10-06 15:01
claiming 900 hypercerts now....

**Comment by bitbeckers** [comment] 2024-04-08 11:28
@holkexyz was this succesful? Otherwise feel free to reopen and assign to roadmap project

**Closed by bitbeckers** 2024-04-08 11:28 UTC
Labels: p1:ready
