### ISSUE TITLE
Bug: banner is stretched in final version, but wasn't in preview

### ISSUE THREAD

**Issue by holkeb** [hypercerts-org/hypercerts#423] opened 2023-03-03 21:26 UTC
The banner of the final hypercert is stretched:

![Image](https://user-images.githubusercontent.com/103380539/222832298-2e41a699-e570-471b-8f1f-7287ba7e9779.png)

However, in the preview we didn't see that it was stretched:

![Image](https://user-images.githubusercontent.com/103380539/222832414-0ef1a628-841f-407d-9836-747bdce4de5f.png)

Picture to reproduce: https://bafybeih2f53s6vewued4saickakmq3i6lnoidh4cf7blv4gcagob6lut6m.ipfs.w3s.link/logo_large.png

**Comment by ryscheng** [comment] 2023-03-16 23:58
Yep, this is a dupe of this issue
https://github.com/hypercerts-org/hypercerts/issues/264

1. At the time we decided just updating clear sizing / aspect ratio requirements for images. It is a reasonable pattern to add validation and just reject any images that don't conform. Not a great UX for sure, but pretty common.

2. Another common pattern is to add an in-browser cropper to force you to crop to the right aspect ratio. This is really common with profile pic uploads.

3. "Fixing the code" involves fixing this library that we use as a black box but did not author ourselves
https://www.npmjs.com/package/html2canvas

I don't think that's a realistic option we'll pursue. My vote is to do option 1 until we decide it's worth the engineering resources to do 2

**Comment by ccerv1** [comment] 2023-03-17 21:14
@holkeb LMK if you are OK with Option 1 and we can close out this issue. If so, then I think it can be addressed in #86

**Comment by holkeb** [comment] 2023-03-21 08:43
I'm ok with all options. And I think we all have the same preference order on the options. So based on resources just doing 1 for now seems right

**Comment by ccerv1** [comment] 2023-03-22 14:13
@ryscheng do you want to proceed with adding image validation:

> At the time we decided just updating clear sizing / aspect ratio requirements for images. It is a reasonable pattern to add validation and just reject any images that don't conform. Not a great UX for sure, but pretty common.

**Comment by holkeb** [comment] 2023-03-29 13:14
@ryscheng this bug came up for a user. Can we notify users when they have uploaded a banner where this would happen? (cc @ccerv1 )



![Image](https://user-images.githubusercontent.com/103380539/228548877-5ac6605e-f2ed-4398-b0bf-1a8805f95570.png)

> I just finished creating it. I want to give feedback that on the preview page, the background image is cropped, which means if the length is more than twice as wide as 2:1, only the middle part will be displayed. But in actual works, if the aspect ratio is not 2:1, it will be squeezed into 2:1. This can cause confusion.

> The first picture is what was displayed when I created it. Although I noticed the hints about ratio, I just assumed that the background image would eventually be cropped to look like what I saw. 😂

**Comment by ryscheng** [comment] 2023-03-29 13:30
Can you link to the image used?

**Comment by holkeb** [comment] 2023-03-29 14:03
I'll ask the project

**Comment by holkeb** [comment] 2023-03-29 14:14
I see the same stretch with this image (as described in the original post of this issue): https://bafybeih2f53s6vewued4saickakmq3i6lnoidh4cf7blv4gcagob6lut6m.ipfs.w3s.link/logo_large.png

**Comment by holkeb** [comment] 2023-03-29 14:23
@ryscheng the project used this one: https://gitcoin.mypinata.cloud/ipfs/bafybeibv622wxhiba7rziwmx4pgyzmevjtycekxwbwn3jjfk7focziiqba

**Comment by ryscheng** [comment] 2023-03-29 16:08
So quick fix, changed the image to be fill in Plasmic v22.0.6 so that it looks weird in the preview too.

**Closed** 2023-04-03 13:34 UTC
Labels: p0:urgent
