### ISSUE TITLE
bug: claims vanishing from the dashboard

### ISSUE THREAD

**Issue by ccerv1** [hypercerts-org/hypercerts#549] opened 2023-04-20 18:54 UTC
### To Reproduce

Very specific case ... see below.

### Describe the Bug

User reported bug:

I went to the site, connected my wallet on Optimism and was shown that I had claimed one of five hypercerts I was entitled to. Easy enough. I pressed the button that said, Claim All (or whatever it said) and submitted a transaction. It all went through perfectly.

When I returned from submitting the transaction (which completed very quickly), the display was only showing the single hypercert that I had already claimed. The other four were no longer displaying as being claimable, but neither were they displaying as having been claimed.

I hit reload, and all five of my now-claimed certs showed up.

### Expected Behavior

The dashboard should reflect the current state of what has been claimed / is claimable for a user with minimal latency. Claims should never be dropped.

**Comment by ryscheng** [comment] 2023-04-21 18:14
This is kinda expected behavior at the moment, since we don't have any way to wait for indexing to complete at the moment.
Filed a feature request to track
https://github.com/hypercerts-org/hypercerts/issues/551

**Comment by ryscheng** [comment] 2023-06-21 03:34
Closing in favor of https://github.com/hypercerts-org/hypercerts/issues/551

**Closed by ryscheng** 2023-06-21 03:34 UTC
