### ISSUE TITLE
Allow manual closing of minting modal

### ISSUE THREAD

**Issue by bitbeckers** [hypercerts-org/hypercerts#607] opened 2023-04-28 11:44 UTC
### Describe the feature you'd like to request

When minting, even with errors or warnings, I cannot exit the minting modal. This locks me out of the interface.
<img width="1676" alt="Screenshot 2023-04-28 at 13 42 44" src="https://user-images.githubusercontent.com/19667964/235138861-851cf408-3d44-4be3-9516-ef7068738036.png">

### Describe the solution you'd like

Allow to click out off the modal by selecting the backdrop or a X-symbol in the corner. Add a hover button that reopens the modal for users to check back in on the state of the transaction.

### Describe alternatives you've considered

F5

**Comment by ryscheng** [comment] 2023-06-21 03:30
Duplicate of https://github.com/hypercerts-org/hypercerts/issues/836

It was an intention decision not to let the user close the modal because users tended to close it and then regret it because they don't have a way to get it back.

I think the better short-term solution is to just close the modal automatically if we encounter and surface an error properly.

**Closed by ryscheng** 2023-06-21 03:30 UTC
