### ISSUE TITLE
fleek is failing to build despite no underlying changes to the contracts

### ISSUE THREAD

**Issue by ccerv1** [hypercerts-org/hypercerts#544] opened 2023-04-19 16:30 UTC
### Which area(s) of Hypercerts are affected? (leave empty if unsure)

Frontend Dapp

### To Reproduce

It appears to be flaky, so not sure exactly how to reproduce. Here is a log of recent builds
<img width="943" alt="image" src="https://user-images.githubusercontent.com/42869436/233140203-20df0d00-fd1d-409a-879f-c31dca4e80fa.png">

### Describe the Bug

Build fails. [Here](https://app.fleek.co/#/sites/hypercerts/deploys/2023-04-19T15:55:33.633Z?accountId=760f99d6-5a41-4a96-81a4-09dd8194b501) is a log

### Expected Behavior

Build not failing :)

**Comment by ryscheng** [comment] 2023-04-19 22:49
Flaky builds, I suspect it has to do with the turbo build not correctly specifying dependencies in the monorepo parallel builds.

**Comment by ryscheng** [comment] 2023-04-20 15:30
Duplicate of https://github.com/hypercerts-org/hypercerts/issues/547

**Closed by ryscheng** 2023-04-20 15:30 UTC
Labels: type:bug
