### ISSUE TITLE
bug: claims created without an allowlist on Optimism do not recognize the creator as the owner

### ISSUE THREAD

**Issue by ccerv1** [hypercerts-org/hypercerts#534] opened 2023-04-14 19:33 UTC

**Comment by ccerv1** [comment] 2023-04-14 19:55
## Issue

A hypercert that is created __without__ an allowlist should recognize the creator as the owner of all 10,000 units. 

The subgraph and block explorer show the owner = creator. However, this is not reflected in Metamask, OpenSea, or in the Hypercert Dapp.

NOTE: this issue only appears to affect the Optimism version of the contract, not the Goerli one.

## Details

This bug was originally identified by a user, who created a hypercert with an allowlist and then sought to transfer it to another wallet address. They were unable to see the token in their Metamask or OpenSea account, despite the transaction record on the block explorer showing it had succeeded and they were the owner.

I tried replicate the bug on Goerli, but the behavior worked as expected. I was then able to replicate it on Optimism.

- [Here](https://hypercerts.org/app/create/#name=Testing%20transferability&description=Testing%20if%20this%20hypercert%20can%20be%20transferred%20on%20OpenSea&logoUrl=https%3A%2F%2Fimgs.search.brave.com%2FsGvVxmaHOLCEADDL7EFxy6BVBIDTLAkzFCEff_oH4Ps%2Frs%3Afit%3A632%3A225%3A1%2Fg%3Ace%2FaHR0cHM6Ly90c2Uy%2FLm1tLmJpbmcubmV0%2FL3RoP2lkPU9JUC5M%2FXzlmam9RblIyRXl0%2FVzRrOE8tQzhnSGFG%2FaiZwaWQ9QXBp&bannerUrl=https%3A%2F%2Fimgs.search.brave.com%2F3XsmSM6rFVv2t4biAsOb-rL2D1DzUZ1WyhONnaOjapY%2Frs%3Afit%3A948%3A225%3A1%2Fg%3Ace%2FaHR0cHM6Ly90c2U0%2FLm1tLmJpbmcubmV0%2FL3RoP2lkPU9JUC50%2FZmprbVdJWTdIaGF5%2Fc1hkZUhsc25RSGFE%2FdCZwaWQ9QXBp&impactScopes%5B0%5D=all&impactTimeEnd=indefinite&workScopes=testnet%0Atransfers&workTimeStart=2023-04-14&workTimeEnd=2023-04-14&rights%5B0%5D=Public%20Display&contributors=hypercerts.eth&agreeContributorsConsent=true&agreeTermsConditions=true&backgroundColor=blue&backgroundVectorArt=contours) is the cert I used to replicate the bug
- [Here](https://opensea.io/assets/optimism/0x822f17a9a5eecfd66dbaff7946a8071c265d1d07/137133793869138200775739966795002589216768) it is on OpenSea
- [Here](https://optimistic.etherscan.io/tx/0x6aa91aa26a161eadad1c3f1a1c75d8c37809fb012d6292317b59c6618b369754) is the transaction showing that I am the creator

Below is a screenshot illustrating the same:

![Image](https://user-images.githubusercontent.com/42869436/232141068-6acdc3b7-b010-43c3-a00d-c2ea870f9fd0.png)

As well as the graph result:

![Image](https://user-images.githubusercontent.com/42869436/232141585-14c1b91c-50c5-4225-bf92-9445833e9351.png)

(the URI points to the correct hypercert metadata on IPFS)

However, here is the screenshot showing that it doesn’t recognize me as the owner on OpenSea:

![Image](https://user-images.githubusercontent.com/42869436/232142367-17f5604b-12af-410f-858f-bf4144267bfe.png)

Compare this to how it looks on OpenSea for the same hypercert, minted on Goerli Testnet:


![Image](https://user-images.githubusercontent.com/42869436/232142639-d978ef83-3e13-4354-a5ab-e69abd75a17e.png)

**Comment by holkeb** [comment] 2023-04-15 17:10
@ccerv1 I was also able to recreate the bug regarding not being recognized as the owner on OpenSea. On the hypercerts dapp dashboard, the "created" tag is missing.

However, I own 100% on the hypercerts dapp individual hypercert view-page and own all fractions there. Is that the case for you as well?

**Comment by ryscheng** [comment] 2023-04-17 17:47
Duplicate of https://github.com/hypercerts-org/hypercerts/issues/528

**Closed by ryscheng** 2023-04-17 17:47 UTC
Labels: category:onchain, p2: grabbag
